## Where the vocab(s) will be written
save_data: None
# Prevent overwriting existing files in the folder
overwrite: True

# filter long examples
src_seq_length: 1010
tgt_seq_length: 1010
src_seq_length_trunc: 1010
tgt_seq_length_trunc: 1010

# common vocabulary for CoCoNut and target
share_vocab: False
dynamic_dict: True
# Corpus opts:
data:
    trn:
        path_src: /root/zwk/NPR_DATA0306/Processed_Tufano/trn.buggy
        path_tgt: /root/zwk/NPR_DATA0306/Processed_Tufano/trn.fix
        transforms: []
        weight: 1
    valid:
        path_src: /root/zwk/NPR_DATA0306/Processed_Tufano/val.buggy
        path_tgt: /root/zwk/NPR_DATA0306/Processed_Tufano/val.fix
        transforms: []

src_vocab_size: 40000
tgt_vocab_size: 40000
src_vocab: /root/zwk/NPR_DATA0306/Processed_Tufano/src.vocab
tgt_vocab: /root/zwk/NPR_DATA0306/Processed_Tufano/tgt.vocab


#model params
global_attention: general
word_vec_size: 256
rnn_size: 256
bridge: true
layers: 2
encoder_type: brnn

#training params
train_steps: 10000
save_checkpoint_steps: 5000
valid_steps: 5000
max_grad_norm: 2
gpu_ranks: 0
world_size: 1
early_stopping: 3
early_stopping_criteria: accuracy
dropout: 0.1
batch_size: 64
valid_batch_size: 32
optim: adagrad
learning_rate: 0.1
adagrad_accumulator_init: 0.1
seed: 912

#model save and log
log_file: /root/zwk/NPR_DATA0306/Processed_Tufano/221_to.log
save_model: /root/zwk/NPR_DATA0306/Processed_Tufano/221_to
tensorboard: True
tensorboard_log_dir: /root/zwk/NPR_DATA0306/Processed_Tufano/221_to.tensorlog