model: /root/zwk/DDPR_DATA/Artifacts/20873_BPE_Tufano_2w/bpe2w_tufano_step_165000.pt
beam_size: 10
n_best: 10
src: /root/zwk/DDPR_DATA/data/Raw_clean/test.buggy.2w.bpe

output: /root/zwk/DDPR_DATA/Artifacts/20873_BPE_Tufano_2w/bpe2w_tufano_step_165000_nb10.pred
gpu: 0
batch_size: 1
max_length: 1510