model: /root/zwk/DDPR_DATA/model/RQ2/20878_CATufano_idiom10w_transformerwv512_step_180000.pt
beam_size: 10
n_best: 10
src: /root/zwk/DDPR_DATA/data/M1000_Tufano_i10w/test.buggy
tgt: /root/zwk/DDPR_DATA/data/M1000_Tufano_i10w/test.fix
output: /root/zwk/DDPR_DATA/Artifacts/20878_CATufano_idiom10w_transformer_wv512/20878_CATufano_idiom10w_transformerwv512best_b10.pred
gpu: 1
batch_size: 5
max_length: 1010