model: /root/zwk/DDPR_DATA/20878_SequenceR_Line/20878_SequenceR_Line_step_85000.pt
beam_size: 10
n_best: 10
src: /root/zwk/DDPR_DATA/data/SequenceR_Line/test.buggy
tgt: /root/zwk/DDPR_DATA/data/SequenceR_Line/test.fix
output: /root/zwk/DDPR_DATA/20878_SequenceR_Line/20878_SequenceR_Line_step_85000_nb10.pred
gpu: 0
batch_size: 2000
batch_type: tokens
max_length: 1010