model: /root/zwk/DDPR_DATA/Artifacts/20889_Tufano_wv512_idiom10w/20889_tufano_wv512_idiom10w_best.pt
beam_size: 10
n_best: 10
src: /root/zwk/DDPR_DATA/data/M1000_Tufano_i10w/test.buggy
output: /root/zwk/DDPR_DATA/Artifacts/20889_Tufano_wv512_idiom10w/20889_tufano_wv512_idiom10w_best_b10.pred
gpu: 0
batch_size: 2048
batch_type: tokens
max_length: 1010