model: /root/zwk/NPR_DATA0306/Processed_SR/save/SR_26/SR_26_step_50000.pt
beam_size: 100
n_best: 100
src: /root/zwk/NPR_DATA0306/Evaluationdata/Benchmark-processed/SequenceR/benchmark.buggy
tgt: /root/zwk/NPR_DATA0306/Evaluationdata/Benchmark-processed/SequenceR/benchmark.fix
output: /root/zwk/NPR_DATA0306/FixResults/Benchmark_SR/21063_SR_26_b100.pred
gpu: 0
batch_size: 2000
batch_type: tokens
max_length: 250