model: /root/zwk/NPR_DATA0306/Processed_SR/save/SR_26/SR_26_step_50000.pt
beam_size: 100
n_best: 100
src: /root/zwk/NPR_DATA0306/Evaluationdata/Diversity-processed/SequenceR/diversity_.buggy
tgt: /root/zwk/NPR_DATA0306/Evaluationdata/Diversity-processed/SequenceR/diversity_.fix
output: /root/zwk/NPR_DATA0306/FixResults/Diversity_SR/21063_SR_26_diversity_b100.pred
gpu: 0
batch_size: 1000
batch_type: tokens
max_length: 250