model: /root/zwk/NPR_DATA0306/Processed_Tufano/save/Tufano_3/Tufano_3_step_50000.pt
beam_size: 100
n_best: 100
src: /root/zwk/NPR_DATA0306/Evaluationdata/Diversity-processed/Tufano/diversity_.buggy

output: /root/zwk/NPR_DATA0306/Processed_Tufano/save/Tufano_3/Tufano_3_nb100_diversity.pred
gpu: 0
batch_size: 600
batch_type: tokens
max_length: 600