model: /root/zwk/NPR_DATA0306/Processed_Tufano/save/Tufano_3/Tufano_3_step_50000.pt
beam_size: 100
n_best: 100
src: /root/zwk/NPR_DATA0306/Evaluationdata/Benchmark-processed/Tufano/benchmark.buggy
output: /root/zwk/NPR_DATA0306/Processed_Tufano/save/Tufano_3/Tufano_3_nb100_benchmark.pred
gpu: 0
batch_size: 1
max_length: 1010