data_path: /home/gehongliang/zwk/Data_Processed/PatchEdits/bears.data
vocab_path: /home/gehongliang/PE/Model/data/temp_vocab
output_path: /home/gehongliang/zwk/NPR4J_Pred/bears.pred
model_path: /home/gehongliang/PE/Model/models-2022
log_path: /home/gehongliang/zwk/NPR4J_Pred/bears.log
beam_size: 300
