validation_repo_root_dir: validation_repo
multi_process_repo_root_dir: multi_validation_repo
d4j_buggy_repo_root_dir: d4j_buggy_repo
d4j_fixed_repo_root_dir: d4j_fix_repo
mutant_root_dir: MutationBenchmark
mutant_patch_root_dir: patch/src_patches
mutant_bin_patch_root_dir: patch/bin_patches
mutant_compile_result_root_dir: patch/compilation_result
d4j_oracle_patch_dir: d4j_scripts/resources/d4j_ori_oracle_patches
compile_log_root_dir: compilation_analysis/log
patch_eq_root_dir: patch_eq_analysis