## Where the vocab(s) will be written
save_data: /home/zhongwenkang/DDPR_DATA/data/L2L_Tufano2w/
# Prevent overwriting existing files in the folder
overwrite: True

# filter long examples
src_seq_length: 1010
tgt_seq_length: 1010
src_seq_length_trunc: 1010
tgt_seq_length_trunc: 1010

# common vocabulary for CoCoNut and target
share_vocab: True
dynamic_dict: True
# Corpus opts:
data:
    train:
        path_src: /home/zhongwenkang/DDPR_DATA/data/L2L_Tufano2w/trn.buggy
        path_tgt: /home/zhongwenkang/DDPR_DATA/data/L2L_Tufano2w/trn.fix
        transforms: []
        weight: 1
    valid:
        path_src: /home/zhongwenkang/DDPR_DATA/data/L2L_Tufano2w/val.buggy
        path_tgt: /home/zhongwenkang/DDPR_DATA/data/L2L_Tufano2w/val.fix
        transforms: []

src_vocab_size: 30000
tgt_vocab_size: 30000
src_vocab: /home/zhongwenkang/DDPR_DATA/data/L2L_Tufano2w/SequenceR_Tufano2w_line.vocab
tgt_vocab: /home/zhongwenkang/DDPR_DATA/data/L2L_Tufano2w/SequenceR_Tufano2w_line.vocab


#log_file

copy_attn: true
copy_loss_by_seqlength: true
reuse_copy_attn: true
global_attention: general
word_vec_size: 512
rnn_size: 512
bridge: true
layers: 2
encoder_type: brnn
early_stopping: 3
early_stopping_criteria: accuracy
train_steps: 500000
valid_steps: 5000
save_checkpoint_steps: 5000
max_grad_norm: 2
dropout: 0.1
batch_size: 32
valid_batch_size: 8
optim: adagrad
learning_rate: 0.15
adagrad_accumulator_init: 0.1

seed: 912
world_size: 1
gpu_ranks: 0

log_file: /home/zhongwenkang/DDPR_DATA/data/L2L_Tufano2w/229_CATufano_2w_SequenceR_Line.log
save_model: /home/zhongwenkang/DDPR_DATA/data/L2L_Tufano2w/229_CATufano_2w_SequenceR_Line
tensorboard: True
tensorboard_log_dir: /home/zhongwenkang/DDPR_DATA/data/L2L_Tufano2w/229_CATufano_2w_SequenceR_Line.tensorlog

