simfix_home: tools/SimFix/SimFix_for_ori
repo_root_dir: tools/SimFix/repo_simfix_ori
failing_tests_dir: tools/PraPR/failing_tests/d4j_ori_failing_tests
output_dir: tools/SimFix/output_d4j_ori
log_dir: tools/SimFix/log_d4j_ori