simfix_home: tools/SimFix/SimFix_for_mutant
repo_root_dir: tools/SimFix/repo_simfix_mutant
failing_tests_dir: tools/PraPR/failing_tests/d4j_mutants_failing_tests
failing_tests_add_dir: tools/PraPR/failing_tests/d4j_mutants_add_failing_tests
output_dir: tools/SimFix/output_1700
output_add_dir: tools/SimFix/output_add
log_dir: tools/SimFix/log_1700
log_add_dir: tools/SimFix/log_add