beam: 300
clearml: false
datadir: /home/zhongwenkang2/RawData_Processed/CoCoNut/qbs
modelpath: /home/zhongwenkang2/NPR4J-Models/CoCoNut/CoCoNut_99_save/checkpoint_best.pt
nbest: 300
outputfile: /home/zhongwenkang2/NPR4J_Pred/CoCoNut/CoCoNut_99_b300_qbs.pred
source: buggy
target: fix
taskname: CoCoNut
use_context: true
