beam: 300
clearml: false
datadir: /home/zhongwenkang2/RawData_Processed/CoCoNut/d4j
modelpath: /home/zhongwenkang2/NPR4J-Models/CoCoNut/CoCoNut_15_save/checkpoint_best.pt
nbest: 300
outputfile: /home/zhongwenkang2/NPR4J_Pred/CoCoNut/CoCoNut_15_b300_d4j.pred
source: buggy
target: fix
taskname: CoCoNut
use_context: true
