beam: 300
clearml: false
datadir: /home/zhongwenkang2/RawData_Processed/CoCoNut/bdj
modelpath: /home/zhongwenkang2/NPR4J-Models/CoCoNut/CoCoNut_context_tune_9_save/checkpoint_best.pt
nbest: 300
outputfile: /home/zhongwenkang2/NPR4J_Pred/CoCoNut/CoCoNut_context_tune_9_b300_bdj.pred
source: buggy
target: fix
taskname: CoCoNut
use_context: true
