alpha_repair_input_dir_d4j_ori: tools/AlphaRepair/input_for_alpha_repair_d4j_ori
result_dir: tools/AlphaRepair/Results-d4j-ori
src_patch_dir: patch/src_d4j_ori_patches/alpha_repair
bug_info_path: tools/AlphaRepair/code/Dataset_d4j_ori/example.json