alpha_repair_input_dir_1700: tools/AlphaRepair/input_for_alpha_repair_1700 # input dir for 1700 bugs in mutation benchmark
alpha_repair_input_dir_add: tools/AlphaRepair/input_for_alpha_repair_add # input dir for 295 additional bugs that can make up a 700 bugs benchmark for mutators (100 bugs each mutator)
result_dir: tools/AlphaRepair/Results-1700
result_add_dir: tools/AlphaRepair/Results-add
src_patch_dir: patch/src_patches/alpha_repair
src_patch_add_dir: patch/src_patches_add/alpha_repair
bug_info_path: tools/AlphaRepair/code/Dataset_1700/example.json
bug_info_add_path: tools/AlphaRepair/code/Dataset_add/example.json