input_csv_path: tools/SelfAPR/input/input_d4j_ori.csv
output_csv_path: tools/SelfAPR/output/output_d4j_ori.csv
tmp_repo_dir: tools/SelfAPR/tmp_repo
src_patch_dir: patch/src_d4j_ori_patches/selfapr_patches
model_dir: tools/SelfAPR/model_SelfAPR