input_csv_path: tools/SelfAPR/input/input_1700.csv
output_csv_path: tools/SelfAPR/output/output_1700.csv
input_add_csv_path: tools/SelfAPR/input/input_add.csv
output_add_csv_path: tools/SelfAPR/output/output_add.csv
tmp_repo_dir: tools/SelfAPR/tmp_repo
src_patch_add_dir: patch/src_patches_add/selfapr_patches
model_dir: tools/SelfAPR/model_SelfAPR