data_path: /home/xxx/research/mutBench/npr4j/ids_all_info/edits/mutBench.data
vocab_path: /home/xxx/research/mutBench/edits/data/model/vocabulary
output_path: /home/xxx/research/mutBench/npr4j/ids_all_info/edits/mutBench.pred
model_path: /home/xxx/research/mutBench/edits/model/models-edits-context
log_path: /home/xxx/research/mutBench/npr4j/ids_all_info/edits/mutBench.log
beam_size: 100
