batch_size: 64
clip_norm: 0.5420129536107342
criterion: cross_entropy
decoder_embed_dim: 480
decoder_layers: '[(512,8)] * 7'
decoder_out_embed_dim: 480
device_id: 0
dropout: 0.47550237851704824
encoder_embed_dim: 480
encoder_layers: '[(384,4)] * 2'
lr: 0.2704405919353996
max-epoch: 20
momentum: 0.3011142108037459
optimizer: sgd
savedir: /root/zwk/DDPR_DATA/CoCoNut/CoCoNut_99_save
share_input_output_embed: 'true'
trainbin: /root/zwk/NPR_DATA0306/Processed_CoCoNut/dest3
