failing_tests_root_dir: tools/PraPR/failing_tests/d4j_mutants_failing_tests
failing_tests_add_root_dir: tools/PraPR/failing_tests/d4j_mutants_add_failing_tests
result_dir: tools/PraPR/result_1700
result_add_dir: tools/PraPR/result_add
pom_root_dir: tools/PraPR/pom-for-prapr-exp