dropout: 0.14750324647058333
share_input_output_embed: True
encoder_embed_dim: 353
decoder_embed_dim: 353
decoder_out_embed_dim: 353
encoder_layers: '[(384,6)] * 8'
decoder_layers: '[(512,10)] * 5'
lr: 0.1628703688177207
momentum:  0.5498989114182679
clip_norm: 0.3526243918050602
optimizer: 'nag'
criterion: 'cross_entropy'
savedir: 'D:\DDPR_DATA\OneLine_Replacement\FConv_line\save'
trainbin: 'D:\DDPR_DATA\OneLine_Replacement\FConv_line\dest'
batch_size: 32
device_id: 0
max-epoch: 30
