log_dir: tools/SequenceR/log/log_1700
log_add_dir: tools/SequenceR/log/log_add
output_dir: tools/SequenceR/output/output_1700
output_add_dir: tools/SequenceR/output/output_add
model_path: tools/SequenceR/model/model.pt
beam_size: 100