diff_dir: tools/RewardRepair/diff/diff_1700
diff_add_dir: tools/RewardRepair/diff/diff_add
input_csv_path: tools/RewardRepair/input/input_1700.csv
input_add_csv_path: tools/RewardRepair/input/input_add.csv
output_csv_path: tools/RewardRepair/output/output_1700.csv
output_add_csv_path: tools/RewardRepair/output/output_add.csv
src_patch_dir: patch/src_patches/reward_repair
src_patch_add_dir: patch/src_patches_add/reward_repair
context_lines: 10